import MainProvider from '@/providers/MainProvider'
import type { Metadata } from 'next'
import { Oswald, Sofia_Sans } from 'next/font/google'
import './globals.scss'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export const sofia = Sofia_Sans({
	subsets: ['latin'],
	display: 'swap',
	weight: ['300', '400', '500', '600', '700']
})

export const oswald = Oswald({
	subsets: ['latin'],
	display: 'swap',
	weight: ['300', '400', '500', '600', '700']
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<MainProvider>{children}</MainProvider>
			</body>
		</html>
	)
}
